[package]
name = "life_simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
egui = "0.21.0"
bevy_egui = "0.19.0"
chrono = "0.4.23"
random-string = "1.0" # Temp
rand = "0.8.5"
